name: Setup VLLM
description: Start VLLM container (non-blocking)
runs:
  using: "composite"
  steps:
    - name: Start VLLM
      shell: bash
      run: |
        # Start vllm container in background (non-blocking)
        docker run -d \
          --name vllm \
          --privileged=true \
          --net=host \
          quay.io/higginsd/vllm-cpu:65393ee064-qwen3 \
          --host 0.0.0.0 \
          --port 8000 \
          --enable-auto-tool-choice \
          --tool-call-parser hermes \
          --model /root/.cache/Qwen3-0.6B \
          --served-model-name Qwen/Qwen3-0.6B \
          --max-model-len 8192
        echo "vLLM container started (starting up in background)..."
