name: Setup VLLM
description: Start VLLM container and wait for it to be ready
runs:
  using: "composite"
  steps:
    - name: Start VLLM
      shell: bash
      run: |
        # Start vllm container in background (non-blocking)
        docker run -d \
          --name vllm \
          --privileged=true \
          --net=host \
          quay.io/higginsd/vllm-cpu:65393ee064-qwen3 \
          --host 0.0.0.0 \
          --port 8000 \
          --enable-auto-tool-choice \
          --tool-call-parser hermes \
          --model /root/.cache/Qwen3-0.6B \
          --served-model-name Qwen/Qwen3-0.6B \
          --max-model-len 8192
        echo "vLLM container started (waiting for it to be ready)..."

    - name: Wait for VLLM to be ready
      shell: bash
      run: |
        echo "Validating vLLM is ready..."
        for i in {1..60}; do
          if curl -fsS http://localhost:8000/health >/dev/null 2>&1; then
            echo "vLLM is ready!"
            exit 0
          fi
          echo "Waiting for vLLM... ($i/60)"
          sleep 2
        done
        echo "vLLM failed to start after 120 seconds"
        docker logs vllm || true
        exit 1
