#!/usr/bin/env python3

import yaml
from pathlib import Path


REPO_ROOT = Path(__file__).parent.parent

STRIPPED_PROVIDER_TYPES = {
    "inline::sentence-transformers",
    "inline::milvus",
    "inline::faiss",
    "inline::localfs",
}

HEADER = (
    "# This file is automatically generated from build.yaml\n"
    "# by scripts/gen_stripped_config.py - do not edit manually.\n"
    "#\n"
    "# Stripped provider types:\n"
)


def gen_stripped_config():
    config_path = REPO_ROOT / "distribution" / "build.yaml"
    output_path = REPO_ROOT / "distribution" / "config.yaml"

    if not config_path.exists():
        print(f"Error: {config_path} not found")
        return 1

    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    providers = config.get("providers", {})
    for api, provider_list in providers.items():
        if isinstance(provider_list, list):
            providers[api] = [
                p
                for p in provider_list
                if not isinstance(p, dict)
                or p.get("provider_type") not in STRIPPED_PROVIDER_TYPES
            ]

    header = HEADER + "".join(
        f"#   - {t}\n" for t in sorted(STRIPPED_PROVIDER_TYPES)
    )

    with open(output_path, "w") as f:
        f.write(header)
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    print(f"Successfully generated {output_path}")
    return 0


if __name__ == "__main__":
    exit(gen_stripped_config())
