#!/usr/bin/env python3

import yaml
from pathlib import Path


REPO_ROOT = Path(__file__).parent.parent


def gen_distro_table(providers_data):
    # Start with table header
    table_lines = ["| API | Provider |", "|-----|----------|"]

    # Create a list to collect all API-Provider pairs for sorting
    api_provider_pairs = []

    # Iterate through each API type and its providers
    for api_name, provider_list in providers_data.items():
        if isinstance(provider_list, list):
            for provider in provider_list:
                if isinstance(provider, dict) and "provider_type" in provider:
                    provider_type = provider["provider_type"]
                    api_provider_pairs.append((api_name, provider_type))

    # Sort first by API name, then by provider type
    api_provider_pairs.sort(key=lambda x: (x[0], x[1]))

    # Add sorted pairs to table
    for api_name, provider_type in api_provider_pairs:
        table_lines.append(f"| {api_name} | {provider_type} |")

    return "\n".join(table_lines)


def gen_distro_docs():
    # define distro run.yaml and README.md paths
    run_yaml_path = REPO_ROOT / "distribution" / "run.yaml"
    readme_path = REPO_ROOT / "distribution" / "README.md"

    # Check if run.yaml exists
    if not run_yaml_path.exists():
        print(f"Error: {run_yaml_path} not found")
        return 1

    # header section
    header = """<!-- This file is automatically generated by scripts/gen_distro_doc.py - do not update manually -->

# Open Data Hub Llama Stack Distribution Image

This image contains the official Open Data Hub Llama Stack distribution, with all the packages and configuration needed to run a Llama Stack server in a containerized environment.

You can see an overview of the APIs and Providers the image ships with in the table below.

"""

    try:
        # Load the run.yaml data
        with open(run_yaml_path, "r") as file:
            run_yaml_data = yaml.safe_load(file)

        # Extract providers section
        providers = run_yaml_data.get("providers", {})

        if not providers:
            print("Error: No providers found in run.yaml")
            return 1

        # Generate the Markdown table
        table_content = gen_distro_table(providers)

        # Write to README.md
        with open(readme_path, "w") as readme_file:
            readme_file.write(header + table_content + "\n")

        print(f"Successfully generated {readme_path}")
        print(
            "Ensure you have checked-in any changes to the README to git, or the pre-commit check using this script will fail"
        )
        return 0

    except Exception as e:
        print(f"Error: {e}")
        return 1


if __name__ == "__main__":
    exit(gen_distro_docs())
